import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SpaceWrapper from "./components/background/SpaceWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"grid grid-rows-1 grid-cols-1"}>
        <div>{children}</div>
        <SpaceWrapper/>
      </body>
    </html>
  );
}
